// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/dashboard": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna metricas administrativas (somente admin)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Dashboard administrativo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.AdminDashboardData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/analyze-job": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Analisa compatibilidade do curriculo com uma vaga usando IA",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Analisar vaga com IA",
                "parameters": [
                    {
                        "description": "ID da vaga",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AnalyzeJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResumeAnalysis"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/analyze-job/send-email": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Envia resultado da analise de compatibilidade por email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Enviar analise por email",
                "parameters": [
                    {
                        "description": "ID da vaga e resultado da analise",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SendAnalysisEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna estatisticas e vagas recentes do usuario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dados do dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DashboardData"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard/jobs": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna vagas com paginacao e filtros",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Vagas recentes paginadas",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Pagina",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limite por pagina (max 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Filtrar por dias",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscar por titulo",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PaginatedJobs"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/getSites": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna todos os sites com status de inscricao do usuario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sites"
                ],
                "summary": "Listar sites de carreiras",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SiteDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Remove o cookie de autenticacao",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout do usuario",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna dados do usuario autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verificar autenticacao",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna historico de notificacoes do usuario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Listar notificacoes",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limite de resultados (max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.NotificationWithJob"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/payments/create/{planId}": {
            "post": {
                "description": "Inicia processo de pagamento para um plano",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Criar pagamento",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do plano",
                        "name": "planId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados de pagamento",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gateway.InitiatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CreatePaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/plans": {
            "get": {
                "description": "Retorna todos os planos de assinatura disponiveis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Plans"
                ],
                "summary": "Listar planos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Plan"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/request-site": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Envia solicitacao de um novo site de carreiras para o admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RequestedSite"
                ],
                "summary": "Solicitar novo site",
                "parameters": [
                    {
                        "description": "URL do site",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RequestedSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/user/change-password": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Altera a senha do usuario autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Alterar senha",
                "parameters": [
                    {
                        "description": "Senhas antiga e nova",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/user/profile": {
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Atualiza nome, telefone e CPF do usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Atualizar perfil",
                "parameters": [
                    {
                        "description": "Dados do perfil",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/validate-checkout": {
            "post": {
                "description": "Verifica se email e CPF ja estao cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Validar dados de checkout",
                "parameters": [
                    {
                        "description": "Email e CPF",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ValidateCheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ValidateCheckoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/webhooks/abacatepay": {
            "post": {
                "description": "Recebe notificacao de pagamento do AbacatePay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "Webhook de pagamento",
                "parameters": [
                    {
                        "description": "Payload do webhook",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gateway.WebhookPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/curriculum": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retorna todos os curriculos do usuario autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Curriculum"
                ],
                "summary": "Listar curriculos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Curriculum"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Cria um novo curriculo para o usuario autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Curriculum"
                ],
                "summary": "Criar curriculo",
                "parameters": [
                    {
                        "description": "Dados do curriculo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Curriculum"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Curriculum"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/curriculum/{id}": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Atualiza um curriculo existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Curriculum"
                ],
                "summary": "Atualizar curriculo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do curriculo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Curriculum"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Curriculum"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/curriculum/{id}/active": {
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Define um curriculo como ativo para o usuario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Curriculum"
                ],
                "summary": "Ativar curriculo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do curriculo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Verifica se a API esta rodando",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HealthResponse"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Verifica se o banco de dados e Redis estao acessiveis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.ReadinessResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica o usuario e retorna JWT em cookie HTTP-only",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login do usuario",
                "parameters": [
                    {
                        "description": "Credenciais de login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cookie Authorization definido",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scrape-sandbox": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Executa scraping de teste com a configuracao fornecida (admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sites"
                ],
                "summary": "Testar scraping (sandbox)",
                "parameters": [
                    {
                        "description": "Configuracao de scraping",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SiteScrapingConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SandboxScrapeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.SandboxScrapeErrorResponse"
                        }
                    }
                }
            }
        },
        "/siteCareer": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Cria nova configuracao de scraping para um site (admin)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sites"
                ],
                "summary": "Adicionar site de carreiras",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JSON da configuracao do site",
                        "name": "siteData",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Logo da empresa",
                        "name": "logo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.SiteScrapingConfig"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/userSite": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Adiciona inscricao do usuario em um site de carreiras",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserSite"
                ],
                "summary": "Inscrever-se em site",
                "parameters": [
                    {
                        "description": "ID do site e palavras-chave",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/userSite/{siteId}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Remove inscricao do usuario em um site de carreiras",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserSite"
                ],
                "summary": "Cancelar inscricao em site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do site",
                        "name": "siteId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Atualiza as palavras-chave de filtragem para um site inscrito",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserSite"
                ],
                "summary": "Atualizar filtros do site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do site",
                        "name": "siteId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Palavras-chave",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserSiteFiltersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gateway.InitiatePaymentRequest": {
            "type": "object",
            "required": [
                "billing_period",
                "cellphone",
                "email",
                "methods",
                "name",
                "password",
                "tax"
            ],
            "properties": {
                "billing_period": {
                    "type": "string",
                    "enum": [
                        "monthly",
                        "annual"
                    ]
                },
                "cellphone": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "tax": {
                    "type": "string"
                }
            }
        },
        "gateway.WebhookBilling": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "customer": {
                    "$ref": "#/definitions/gateway.WebhookBillingCustomer"
                },
                "externalId": {
                    "description": "nosso pendingRegistrationID",
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "paidAmount": {
                    "type": "integer"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gateway.WebhookBillingProduct"
                    }
                },
                "status": {
                    "description": "\"PAID\"",
                    "type": "string"
                }
            }
        },
        "gateway.WebhookBillingCustomer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "description": "contém email, name, cellphone, taxId",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "gateway.WebhookBillingProduct": {
            "type": "object",
            "properties": {
                "externalId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "gateway.WebhookData": {
            "type": "object",
            "properties": {
                "billing": {
                    "$ref": "#/definitions/gateway.WebhookBilling"
                },
                "payment": {
                    "$ref": "#/definitions/gateway.WebhookPayment"
                }
            }
        },
        "gateway.WebhookPayload": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/gateway.WebhookData"
                },
                "devMode": {
                    "type": "boolean"
                },
                "event": {
                    "description": "\"billing.paid\", \"withdraw.done\", etc.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "gateway.WebhookPayment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "fee": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                }
            }
        },
        "model.AdminDashboardData": {
            "type": "object",
            "properties": {
                "active_users": {
                    "type": "integer"
                },
                "monitored_sites": {
                    "type": "integer"
                },
                "recent_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ScrapingError"
                    }
                },
                "scraping_errors": {
                    "type": "integer"
                },
                "total_revenue": {
                    "type": "number"
                }
            }
        },
        "model.AnalyzeJobRequest": {
            "type": "object",
            "required": [
                "job_id"
            ],
            "properties": {
                "job_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "model.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "senhaNova456"
                },
                "old_password": {
                    "type": "string",
                    "example": "senhaAntiga123"
                }
            }
        },
        "model.CreatePaymentResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://abacatepay.com/billing/abc123"
                }
            }
        },
        "model.Curriculum": {
            "type": "object",
            "properties": {
                "educations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Education"
                    }
                },
                "experiences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Experience"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "languages": {
                    "type": "string"
                },
                "skills": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.DashboardData": {
            "type": "object",
            "properties": {
                "alerts_sent_count": {
                    "type": "integer"
                },
                "latest_jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Job"
                    }
                },
                "monitored_urls_count": {
                    "type": "integer"
                },
                "new_jobs_today_count": {
                    "type": "integer"
                },
                "user_monitored_urls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MonitoredURL"
                    }
                }
            }
        },
        "model.Education": {
            "type": "object",
            "properties": {
                "degree": {
                    "type": "string"
                },
                "institution": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "mensagem de erro"
                }
            }
        },
        "model.Experience": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Gap": {
            "type": "object",
            "properties": {
                "areaDescription": {
                    "type": "string"
                },
                "jobRequirementImpacted": {
                    "type": "string"
                }
            }
        },
        "model.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "UP"
                }
            }
        },
        "model.Job": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "job_id": {
                    "type": "integer"
                },
                "job_link": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "site_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "senha123"
                }
            }
        },
        "model.MatchAnalysis": {
            "type": "object",
            "properties": {
                "overallScoreNumeric": {
                    "type": "integer"
                },
                "overallScoreQualitative": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "model.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operação realizada com sucesso"
                }
            }
        },
        "model.MonitoredURL": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                }
            }
        },
        "model.NotificationWithJob": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "job_company": {
                    "type": "string"
                },
                "job_id": {
                    "type": "integer"
                },
                "job_link": {
                    "type": "string"
                },
                "job_location": {
                    "type": "string"
                },
                "job_title": {
                    "type": "string"
                },
                "notified_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.PaginatedJobs": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Job"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "model.Plan": {
            "type": "object",
            "properties": {
                "features": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "max_ai_analyses": {
                    "type": "integer"
                },
                "max_sites": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "model.ReadinessResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "UP"
                },
                "redis": {
                    "type": "string",
                    "example": "UP"
                }
            }
        },
        "model.RequestedSiteRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://careers.google.com"
                }
            }
        },
        "model.ResumeAnalysis": {
            "type": "object",
            "properties": {
                "actionableResumeSuggestions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Suggestion"
                    }
                },
                "finalConsiderations": {
                    "type": "string"
                },
                "gapsAndImprovementAreas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Gap"
                    }
                },
                "matchAnalysis": {
                    "$ref": "#/definitions/model.MatchAnalysis"
                },
                "strengthsForThisJob": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Strength"
                    }
                }
            }
        },
        "model.SandboxScrapeErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "falha ao executar scraping"
                },
                "message": {
                    "type": "string",
                    "example": "erro no scraping"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "model.SandboxScrapeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Job"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Scraping concluído com sucesso"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.ScrapingError": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "site_name": {
                    "type": "string"
                }
            }
        },
        "model.SendAnalysisEmailRequest": {
            "type": "object",
            "required": [
                "analysis",
                "job_id"
            ],
            "properties": {
                "analysis": {
                    "$ref": "#/definitions/model.ResumeAnalysis"
                },
                "job_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "model.SiteDTO": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string",
                    "example": "https://carreiras.ifood.com.br"
                },
                "is_subscribed": {
                    "type": "boolean",
                    "example": true
                },
                "logo_url": {
                    "type": "string",
                    "example": "https://s3.amazonaws.com/logos/ifood.webp"
                },
                "site_id": {
                    "type": "integer",
                    "example": 1
                },
                "site_name": {
                    "type": "string",
                    "example": "iFood"
                }
            }
        },
        "model.SiteScrapingConfig": {
            "type": "object",
            "properties": {
                "api_endpoint_template": {
                    "type": "string"
                },
                "api_headers_json": {
                    "type": "string"
                },
                "api_method": {
                    "type": "string"
                },
                "api_payload_template": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "job_description_selector": {
                    "type": "string"
                },
                "job_list_item_selector": {
                    "type": "string"
                },
                "job_requisition_id_selector": {
                    "type": "string"
                },
                "json_data_mappings": {
                    "type": "string"
                },
                "link_attribute": {
                    "type": "string"
                },
                "link_selector": {
                    "type": "string"
                },
                "location_selector": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "next_page_selector": {
                    "type": "string"
                },
                "scraping_type": {
                    "description": "'HTML', 'API', 'HEADLESS'",
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "title_selector": {
                    "type": "string"
                }
            }
        },
        "model.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "received"
                }
            }
        },
        "model.Strength": {
            "type": "object",
            "properties": {
                "point": {
                    "type": "string"
                },
                "relevanceToJob": {
                    "type": "string"
                }
            }
        },
        "model.Suggestion": {
            "type": "object",
            "properties": {
                "curriculumSectionToApply": {
                    "type": "string"
                },
                "exampleWording": {
                    "type": "string"
                },
                "reasoningForThisJob": {
                    "type": "string"
                },
                "suggestion": {
                    "type": "string"
                }
            }
        },
        "model.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "user_name"
            ],
            "properties": {
                "cellphone": {
                    "type": "string",
                    "example": "11999998888"
                },
                "tax": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "user_name": {
                    "type": "string",
                    "example": "João Silva"
                }
            }
        },
        "model.UpdateUserSiteFiltersRequest": {
            "type": "object",
            "properties": {
                "target_words": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "cellphone": {
                    "type": "string"
                },
                "curriculum_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "plan": {
                    "$ref": "#/definitions/model.Plan"
                },
                "plan_id": {
                    "type": "integer"
                },
                "tax": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "model.UserSiteRequest": {
            "type": "object",
            "properties": {
                "site_id": {
                    "type": "integer"
                },
                "target_words": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ValidateCheckoutRequest": {
            "type": "object",
            "required": [
                "email",
                "tax"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "tax": {
                    "type": "string",
                    "example": "123.456.789-00"
                }
            }
        },
        "model.ValidateCheckoutResponse": {
            "type": "object",
            "properties": {
                "email_exists": {
                    "type": "boolean",
                    "example": false
                },
                "tax_exists": {
                    "type": "boolean",
                    "example": false
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ScrapJobs API",
	Description:      "API para plataforma de scraping e matching de vagas de emprego.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
